version: '3'
services:
  emscripten:
    build:
      context: ../
      dockerfile: tools/Dockerfile.emscripten
    image: emscripten-container
    volumes:
      - emscripten-data:/app

  nginx:
    build:
      context: ../
      dockerfile: tools/Dockerfile.nginx
    image: nginx-container
    ports:
      - "8080:80"
    depends_on:
      - emscripten
    volumes:
      - emscripten-data:/usr/share/nginx/html

volumes:
  emscripten-data:
