FROM nginx:stable-alpine-slim

EXPOSE 80

COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=emscripten-container /app/*.html /usr/share/nginx/html/
COPY --from=emscripten-container /app/*.js /usr/share/nginx/html/
COPY --from=emscripten-container /app/*.wasm /usr/share/nginx/html/

CMD ["nginx", "-g", "daemon off;"]
